spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: scott
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: 8090

mybatis:
  # mapper.xml location Setting
  mapper-locations: mybatis/mapper/*.xml
  # alias Setting
  type-aliases-package: com.multi.restproduct
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # SQL 로그 출력을 위한 설정

image:
  add-resource-locations: /productimgs/
  add-resource-handler: /productimgs/**

  # image-dir : 파일 저장 경로
  # image-url : 프론트에서 접근경로
  image-dir: /productimgs/
  image-url: http://localhost:8090/productimgs/
