server:
  port: 8081 # 들여쓰기는 띄어쓰기 2칸, 값 입력할 때는 한 칸.

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: scott
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis 관련 설정
mybatis:
  mapper-locations: classpath:mappers/*.xml # 매퍼 XML 파일 경로
  configuration:
    map-underscore-to-camel-case: true  # 언더스코어(_)를 카멜케이스로 자동 매핑
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # SQL 로그 출력을 위한 설정